# Generated by Django 5.0.6 on 2024-06-18 09:44

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_profileimg_profile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4919bf55-3506-4127-8db6-e3924adfb5b8'), primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 18, 11, 44, 41, 378114))),
                ('num_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
