# Generated by Django 5.0.6 on 2024-06-20 13:25

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount_alter_post_created_at_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discipline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 15, 25, 58, 614180)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c339035a-1ec9-4c48-966e-20ae4499bee7'), primary_key=True, serialize=False),
        ),
    ]
