# Generated by Django 5.0.6 on 2024-06-20 15:03

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_discipline_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Professional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 3, 34, 350892)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00c3127a-d3bf-42a7-a8aa-b2194aa06a37'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Palmares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fights', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('federation', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
