# Generated by Django 5.0.6 on 2024-06-20 15:15

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_professional_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palmares',
            name='professional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 15, 34, 325946)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe315ea6-03f0-4a25-a6dd-d11d9a6e21ce'), primary_key=True, serialize=False),
        ),
    ]
