# Generated by Django 5.0.6 on 2024-06-20 15:21

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_palmares_professional_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palmares',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='fights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palmares',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 21, 58, 387366)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('384b763d-f528-4501-884e-b747a052361c'), primary_key=True, serialize=False),
        ),
    ]
