# Generated by Django 5.0.6 on 2024-06-20 15:22

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_palmares_draw_alter_palmares_fights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 17, 22, 7, 72133)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa8b6822-9fe3-4733-bf36-24a43d72c6ea'), primary_key=True, serialize=False),
        ),
    ]
