# Generated by Django 5.0.6 on 2024-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_comments',
            field=models.BooleanField(default=True),
        ),
    ]
